# 主流应用直连规则(避免被误代理掉)
payload:
  - DOMAIN,alipay.com
  - DOMAIN,alipay.cn
  - DOMAIN,alibaba.com
  - DOMAIN,alicdn.com
  - DOMAIN,aliyun.com
  - DOMAIN,baidu.com
  - DOMAIN,bdimg.com
  - DOMAIN,bdstatic.com
  - DOMAIN,qq.com
  - DOMAIN,weixin.qq.com
  - DOMAIN,wechat.com
  - DOMAIN,tencent.com
  - DOMAIN,tencent-cloud.com
  - DOMAIN,taobao.com
  - DOMAIN,tmall.com
  - DOMAIN,jd.com
  - DOMAIN,360.cn
  - DOMAIN,360safe.com
  - DOMAIN,douyin.com
  - DOMAIN,bytedance.com
  - DOMAIN,byted.org
  - DOMAIN,huya.com
  - DOMAIN,yy.com
  - DOMAIN,bilibili.com
  - DOMAIN,bilivideo.com
  - DOMAIN,hdslb.com
  - DOMAIN,163.com
  - DOMAIN,126.com
  - DOMAIN,126.net
  - DOMAIN,youku.com
  - DOMAIN,tudou.com
  - DOMAIN,iqiyi.com
  - DOMAIN,qiyi.com
  - DOMAIN,xigua.com
  - PROCESS-NAME,WeChat
  - PROCESS-NAME,WeChatAppEx
  - PROCESS-NAME,QQ